name: Run test happywork-cms

on:
  workflow_call:
    inputs:
      api-url:
        required: true
        type: string

jobs:
  execute-run-test:
    runs-on: ubuntu-latest

    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP PNPM
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 10
          run_install: false

      - name: INSTALL NODEJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: CREATE ENV FILE
        run: echo "NEXT_PUBLIC_API_URL=${{ inputs.api-url }}" > .env

      - name: INSTALL DEPENDENCIES
        run: pnpm i --frozen-lockfile

      - name: RUN LINT
        run: pnpm lint

      - name: RUN TEST
        run: pnpm test
