name: Build happywork-cms

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      mySecrets:
        required: false

jobs:
  execute-build:
    runs-on: ubuntu-latest

    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP PNPM
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 10
          run_install: false

      - name: INSTALL NODEJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: INSTALL DEPENDENCIES
        run: pnpm i --frozen-lockfile

      - name: CREATE ENV FILE
        run: |
          echo -e "${{ inputs.env }}" >> $GITHUB_ENV
          echo -e "${{ secrets.mySecrets }}" >> $GITHUB_ENV

      - name: BUILD PROJECT
        run: pnpm build

      - name: UPLOAD BUILD OUTPUT
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: out
