name: Deploy happywork-cms to Cloudflare Pages

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      branch:
        required: true
        type: string
      cloudflare-page-name:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

jobs:
  execute-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: DOWNLOAD BUILD OUTPUT
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: out

      - name: DEPLOY TO CLOUDFLARE PAGES
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=${{ inputs.cloudflare-page-name }} --branch ${{ inputs.branch }} ./out
