name: Deploy happywork-cms to Cloudflare Pages

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      branch:
        required: true
        type: string
      cloudflare-page-name:
        required: true
        type: string
      aws-account-id:
        required: true
        type: string

jobs:
  execute-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: DOWNLOAD BUILD OUTPUT
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: out

      - name: GET CLOUDFLARED API TOKEN
        run: echo "input branch=${{ inputs.branch }} input cloudflare-page-name=${{ inputs.cloudflare-page-name }} input artifact-name=${{ inputs.artifact-name }}"

      - name: CONFIGURE AWS CREDENTIALS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-action-frontend
          aws-region: ap-southeast-1

      - name: GET CLOUDFLARE SECRETS FROM AWS SECRETS MANAGER
        id: get-cloudflare-secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: cloudflare-credentials
          parse-json-secrets: true

      - name: CLOUDFLARED API TOKEN
        run: echo "CLOUDFLARE_API_TOKEN=${{ steps.get-cloudflare-secret.outputs.CLOUDFLARE_API_TOKEN }}"

      - name: DEPLOY TO CLOUDFLARE PAGES
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ steps.get-cloudflare-secret.outputs.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ steps.get-cloudflare-secret.outputs.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=${{ inputs.cloudflare-page-name }} --branch ${{ inputs.branch }} ./out
