name: Deploy happywork-cms to Cloudflare Pages

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      cloudflare-page-name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  run-test:
    uses: JenosizeHW/happywork-github-reuse-workflow/.github/workflows/happywork-cms-test.yaml@main

  build:
    needs: ["run-test"]
    uses: JenosizeHW/happywork-github-reuse-workflow/.github/workflows/happywork-cms-build.yaml@main
    with:
      artifact-name: ${{ inputs.artifact-name }}

  deploy:
    needs: ["build"]
    uses: JenosizeHW/happywork-github-reuse-workflow/.github/workflows/happywork-cms-deploy.yaml@main
    with:
      branch: ${{ inputs.branch }}
      cloudflare-page-name: ${{ inputs.cloudflare-page-name }}
      artifact-name: ${{ inputs.artifact-name }}

  run-semantic-release:
    needs: ["deploy"]
    uses: JenosizeHW/happywork-github-reuse-workflow/.github/workflows/semantic-release.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
