name: Update image

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      tag:
        required: true
        type: string
      env:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      API_KEY:
        required: true

jobs:
  change-image-tag-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Image in Terragrunt
        run: |
          sed -i -E 's|tag:\s"(.*)"|tag: "${{ inputs.tag }}"|g' ./${{ inputs.path }}

      

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: 🎡 update image ${{ inputs.env }} with ${{ inputs.tag }}'
          branch: ${{ inputs.branch }}
          token: ${{ secrets.GH_PAT }}